x-default-logging:
  &default-logging
  driver: local
  options:
    max-size: "1m"
    max-file: "3"

name: poc_service
services:
  proxy:
    container_name: poc_service_proxy
    profiles: [ "serve" ]
    build:
      context: .docker/proxy/traefik
    command:
      - "--accesslog"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=poc-service"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashbord-proxy.entrypoints=web"
      - "traefik.http.routers.dashbord-proxy.rule=Host(`traefik.localhost`)"
      - "traefik.http.services.dashbord-proxy.loadbalancer.server.port=8080"
    networks:
      - poc-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging: *default-logging

  agw:
    container_name: poc_service_agw
    profiles: [ "serve" ]
    build:
      context: .docker/agw/krakend
    depends_on:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agw.entrypoints=web"
      - "traefik.http.routers.agw.rule=Host(`api.localhost`)"
      - "traefik.http.services.agw.loadbalancer.server.port=8080"
    networks:
      - poc-service
    volumes:
      - .docker/agw/krakend/conf/krakend.json:/etc/krakend/krakend.json
    logging: *default-logging

networks:
  poc-service:
    external: true
