name: poc_service
services:
  proxy:
    container_name: poc_proxy
    profiles: [ "serve" ]
    build:
      context: .docker/proxy/traefik
    command:
      - "--accesslog"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=poc-service"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=DEBUG"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--entryPoints.metrics.address=:8899"
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashbord-proxy.entrypoints=web"
      - "traefik.http.routers.dashbord-proxy.rule=Host(`traefik.localhost`)"
      - "traefik.http.services.dashbord-proxy.loadbalancer.server.port=8080"
    networks:
      - poc-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  agw:
    container_name: poc_agw
    profiles: [ "serve" ]
    build:
      context: .docker/agw/krakend
    depends_on:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agw.entrypoints=web"
      - "traefik.http.routers.agw.rule=Host(`api.localhost`)"
      - "traefik.http.services.agw.loadbalancer.server.port=8080"
    networks:
      - poc-service
    volumes:
      - .docker/agw/krakend/conf/krakend.json:/etc/krakend/krakend.json

  victorialogs:
    container_name: poc_victorialogs
    profiles: [ "serve" ]
    build:
      context: .docker/metrics/victoriametrics/logs
    command:
      - "--storageDataPath=/vlogs"
      - "--httpListenAddr=:9428"
    volumes:
      - vldata:/vlogs
    networks:
      - poc-service

  victoriametrics:
    container_name: poc_victoriametrics
    profiles: [ "serve" ]
    build:
      context: .docker/metrics/victoriametrics
    depends_on:
      - proxy
    volumes:
      - vmdata:/storage
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
    networks:
      - poc-service

  fluentbit:
    container_name: poc_fluentbit
    profiles: [ "serve" ]
    build:
      context: .docker/metrics/fluentbit
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - .docker/metrics/fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - victorialogs
    networks:
      - poc-service

  vmagent:
    container_name: poc_vmagent
    profiles: [ "serve" ]
    build:
      context: .docker/metrics/victoriametrics/vmagent
    depends_on:
      - victoriametrics
    volumes:
      - vmagentdata:/vmagentdata
      - .docker/metrics/victoriametrics/vmagent/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://poc_victoriametrics:8428/api/v1/write"
    networks:
      - poc-service

  grafana:
    container_name: poc_grafana
    profiles: [ "serve" ]
    build:
      context: .docker/metrics/grafana
    depends_on:
      - victoriametrics
      - victorialogs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    environment:
      - "GF_INSTALL_PLUGINS=https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.6.2/victorialogs-datasource-v0.6.2.zip;victorialogs-datasource"
      - "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=victorialogs-datasource"
    volumes:
      - grafanadata:/var/lib/grafana
      - .docker/metrics/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - .docker/metrics/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - .docker/metrics/grafana/plugins/:/var/lib/grafana/plugins
      - .docker/metrics/grafana/dashboards/victoriametrics.json:/var/lib/grafana/dashboards/vm.json
      - .docker/metrics/grafana/dashboards/victorialogs.json:/var/lib/grafana/dashboards/vl.json
      - .docker/metrics/grafana/dashboards/traefik.json:/var/lib/grafana/dashboards/proxy.json
      - .docker/metrics/grafana/dashboards/krakend.json:/var/lib/grafana/dashboards/agw.json
    networks:
      - poc-service

volumes:
  vmdata: {}
  vldata: {}
  vmagentdata: {}
  grafanadata: {}

networks:
  poc-service:
    external: true
