apiVersion: 1

datasources:
  - name: VictoriaLogs
    type: victorialogs-datasource
    access: proxy
    url:  http://poc_victorialogs:9428
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://poc_victoriametrics:8428
    isDefault: true
    jsonData:
      prometheusType: Prometheus
      prometheusVersion: 2.24.0
